<article class="doc">
 <h1 class="page">
  Exception Clause
 </h1>
 <div id="preamble">
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     You can use the
     <em>
      Exception Clause
     </em>
     in the Java
     <a class="xref page" href="dsl.html">
      DSL
     </a>
     to specify the error handling you require on a per exception type basis using the
     <strong>
      <code>
       onException()
      </code>
     </strong>
     method. To get started we give quick sample before digging into how it works.
    </p>
   </div>
   <div class="paragraph">
    <p>
     For example if you want to perform a specific piece of processing if a certain exception is raised you can do this simply via:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">onException(ValidationException.class)
    .to("activemq:validationFailed");

from("seda:inputA")
    .to("validation:foo/bar.xsd", "activemq:someQueue");

from("seda:inputB")
    .to("direct:foo")
    .to("rnc:mySchema.rnc", "activemq:anotherQueue");</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     Here if the processing of
     <strong>
      <code>
       seda:inputA
      </code>
     </strong>
     or
     <strong>
      <code>
       seda:inputB
      </code>
     </strong>
     cause a
     <strong>
      <code>
       ValidationException
      </code>
     </strong>
     to be thrown (such as due to the XSD validation of the
     <a class="xref page" href="../components/4.10.x/validator-component.html">
      Validation
     </a>
     component), then the message will be sent to the
     <strong>
      <code>
       activemq:validationFailed
      </code>
     </strong>
     queue.
    </p>
   </div>
   <div class="paragraph">
    <p>
     You can define multiple
     <strong>
      <code>
       onException
      </code>
     </strong>
     clauses for different behavior:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">onException(ValidationException.class)
    .to("activemq:validationFailed");

onException(ShipOrderException.class)
    .to("activemq:shipFailed");

from("seda:order")
    .to("bean:processOrder");</code></pre>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_scopes">
   <a class="anchor" href="#_scopes">
   </a>
   Scopes
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     Exception clauses is scoped as either:
    </p>
   </div>
   <div class="ulist">
    <ul>
     <li>
      <p>
       global (for Java DSL that is per
       <strong>
        <code>
         RouteBuilder
        </code>
       </strong>
       instances, to reuse, see note below)
      </p>
     </li>
     <li>
      <p>
       or route specific
      </p>
     </li>
    </ul>
   </div>
   <div class="paragraph">
    <p>
     Where the
     <strong>
      global
     </strong>
     are the simplest and most easy to understand. In the advanced section we dig into the route specific and even combining them. However
    </p>
   </div>
   <div class="paragraph">
    <p>
     Global scope for Java DSL is per
     <strong>
      <code>
       RouteBuilder
      </code>
     </strong>
     instance, so if you want to share among multiple
     <strong>
      <code>
       RouteBuilder
      </code>
     </strong>
     classes, then create a base abstract
     <strong>
      <code>
       RouteBuilder
      </code>
     </strong>
     class and put the error handling logic in its
     <strong>
      <code>
       configure
      </code>
     </strong>
     method. And then extend this class, and make sure to class
     <strong>
      <code>
       super.configure()
      </code>
     </strong>
     . We are just using the Java inheritance technique.
    </p>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_how_does_camel_select_which_clause_should_handle_a_given_thrown_exception">
   <a class="anchor" href="#_how_does_camel_select_which_clause_should_handle_a_given_thrown_exception">
   </a>
   How Does Camel Select Which Clause Should Handle a Given Thrown Exception?
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     Camel uses
     <strong>
      <code>
       DefaultExceptionPolicyStrategy
      </code>
     </strong>
     to determine a strategy how an exception being thrown should be handled by which
     <strong>
      <code>
       onException
      </code>
     </strong>
     clause. The strategy is:
    </p>
   </div>
   <div class="ulist">
    <ul>
     <li>
      <p>
       the order in which the
       <strong>
        <code>
         onException
        </code>
       </strong>
       is configured takes precedence. Camel will test from first…​last defined.
      </p>
     </li>
     <li>
      <p>
       Camel will start from the bottom (nested caused by) and recursive up in the exception hierarchy to find the first matching
       <strong>
        <code>
         onException
        </code>
       </strong>
       clause.
      </p>
     </li>
     <li>
      <p>
       <strong>
        <code>
         instanceof
        </code>
       </strong>
       test is used for testing the given exception with the
       <strong>
        <code>
         onException
        </code>
       </strong>
       clause defined exception list. An exact
       <strong>
        <code>
         instanceof
        </code>
       </strong>
       match will always be used, otherwise the
       <strong>
        <code>
         onException
        </code>
       </strong>
       clause that has an exception that is the closets super of the thrown exception is selected (recurring up the exception hierarchy).
      </p>
     </li>
    </ul>
   </div>
   <div class="paragraph">
    <p>
     This is best illustrated with an exception:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">onException(IOException.class)
    .maximumRedeliveries(3);

onException(OrderFailedException.class)
    .maximumRedeliveries(2);</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     In the sample above we have defined two exceptions in which
     <strong>
      <code>
       IOException
      </code>
     </strong>
     is first, so Camel will pickup this exception if there is a match.
     <strong>
      <code>
       IOException
      </code>
     </strong>
     that is more general is selected then.
    </p>
   </div>
   <div class="paragraph">
    <p>
     So if an exception is thrown with this hierarchy:
    </p>
   </div>
   <div class="literalblock">
    <div class="content">
     <pre>+ RuntimeCamelException (wrapper exception by Camel)
    + OrderFailedException
        + IOException
            + FileNotFoundException</pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     Then Camel will try testing the exception in this order:
     <strong>
      <code>
       FileNotFoundException
      </code>
     </strong>
     ,
     <strong>
      <code>
       IOException
      </code>
     </strong>
     ,
     <strong>
      <code>
       OrderFailedException
      </code>
     </strong>
     and
     <strong>
      <code>
       RuntimeCamelException
      </code>
     </strong>
     . As we have defined a
     <strong>
      <code>
       onException(IOException.class)
      </code>
     </strong>
     Camel will select this as it’s the
     <strong>
      closest
     </strong>
     match.
    </p>
   </div>
   <div class="paragraph">
    <p>
     If we add a third
     <strong>
      <code>
       onException
      </code>
     </strong>
     clause with the
     <strong>
      <code>
       FileNotFoundException
      </code>
     </strong>
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">onException(IOException.class)
    .maximumRedeliveries(3);

onException(OrderFailedException.class)
    .maximumRedeliveries(2);

onException(FileNotFoundException.class)
    .handled(true)
    .to("log:nofile");</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     Then with the previous example Camel will now use the last
     <strong>
      <code>
       onException(FileNotFoundException.class)
      </code>
     </strong>
     as its an
     <strong>
      exact
     </strong>
     match. Since this is an exact match it will override the general
     <strong>
      <code>
       IOException
      </code>
     </strong>
     that was used before to handle the same exception thrown.
    </p>
   </div>
   <div class="paragraph">
    <p>
     Now a new situation if this exception was thrown instead:
    </p>
   </div>
   <div class="literalblock">
    <div class="content">
     <pre>+ RuntimeCamelException (wrapper exception by Camel)
    + OrderFailedException
        + OrderNotFoundException</pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     Then the
     <strong>
      <code>
       onException(OrderFailedException.class)
      </code>
     </strong>
     will be selected - no surprise here.
    </p>
   </div>
   <div class="paragraph">
    <p>
     And this last sample demonstrates the
     <strong>
      <code>
       instanceof
      </code>
     </strong>
     test aspect in which Camel will select an exception if it’s an instance of the defined exception in the
     <strong>
      <code>
       onException
      </code>
     </strong>
     clause. Illustrated as:
    </p>
   </div>
   <div class="literalblock">
    <div class="content">
     <pre>+ RuntimeCamelException (wrapper exception by Camel)
    + SocketException</pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     Since
     <strong>
      <code>
       SocketException
      </code>
     </strong>
     is an
     <strong>
      <code>
       instanceof IOException
      </code>
     </strong>
     , Camel will select the
     <strong>
      <code>
       onException(IOException.class)
      </code>
     </strong>
     clause.
    </p>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_configuring_redeliverypolicy_redeliver_options">
   <a class="anchor" href="#_configuring_redeliverypolicy_redeliver_options">
   </a>
   Configuring RedeliveryPolicy (redeliver options)
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     <a href="https://www.javadoc.io/doc/org.apache.camel/camel-base/current/org/apache/camel/processor/errorhandler/RedeliveryPolicy.html">
      RedeliveryPolicy
     </a>
     requires to use the
     <a class="xref page" href="../components/4.10.x/eips/dead-letter-channel.html">
      Dead Letter Channel
     </a>
     as the
     <a class="xref page" href="error-handler.html">
      Error Handler
     </a>
     . Dead Letter Channel supports attempting to redeliver the message exchange a number of times before sending it to a dead letter endpoint. See
     <a class="xref page" href="../components/4.10.x/eips/dead-letter-channel.html">
      Dead Letter Channel
     </a>
     for further information about redeliver and which redeliver options exists.
    </p>
   </div>
   <div class="sect2">
    <h3 id="_no_redelivery_is_default_for_onexception">
     <a class="anchor" href="#_no_redelivery_is_default_for_onexception">
     </a>
     No redelivery is default for onException
    </h3>
    <div class="paragraph">
     <p>
      By default, any
      <a href="#">
       Exception Clause
      </a>
      will
      <strong>
       not
      </strong>
      redeliver! (as it sets the
      <code>
       maximumRedeliveries
      </code>
      option to 0).
     </p>
    </div>
    <div class="paragraph">
     <p>
      Sometimes you want to configure the redelivery policy on a per exception type basis. By default in the top examples, if an
      <strong>
       <code>
        org.apache.camel.ValidationException
       </code>
      </strong>
      occurs then the message will not be redelivered; however if some other exception occurs, e.g.,
      <strong>
       <code>
        IOException
       </code>
      </strong>
      or whatever, the route will be retried according to the settings from the
      <a class="xref page" href="../components/4.10.x/eips/dead-letter-channel.html">
       Dead Letter Channel
      </a>
      .
     </p>
    </div>
    <div class="paragraph">
     <p>
      However if you want to customize any methods on the
      <a href="https://www.javadoc.io/doc/org.apache.camel/camel-base/current/org/apache/camel/processor/errorhandler/RedeliveryPolicy.html">
       RedeliveryPolicy
      </a>
      object, you can do this via the fluent API. So lets retry in case of
      <strong>
       <code>
        org.apache.camel.ValidationException
       </code>
      </strong>
      up till two times.
     </p>
    </div>
    <div class="paragraph">
     <p>
      <strong>
       Java DSL
      </strong>
      :
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">onException(ValidationException.class)
    .maximumRedeliveries(2);</code></pre>
     </div>
    </div>
    <div class="paragraph">
     <p>
      <strong>
       XML DSL
      </strong>
      :
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml">&lt;onException&gt;
    &lt;exception&gt;com.mycompany.ValidationException&lt;/exception&gt;
    &lt;redeliveryPolicy maximumRedeliveries="2"/&gt;
&lt;/onException&gt;</code></pre>
     </div>
    </div>
    <div class="paragraph">
     <p>
      You can customize any of the
      <a href="https://www.javadoc.io/doc/org.apache.camel/camel-base/current/org/apache/camel/processor/errorhandler/RedeliveryPolicy.html">
       RedeliveryPolicy
      </a>
      so we can for instance set a different delay of
      <strong>
       <code>
        5000
       </code>
      </strong>
      millis:
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml">&lt;onException&gt;
    &lt;exception&gt;com.mycompany.ValidationException&lt;/exception&gt;
    &lt;redeliveryPolicy maximumRedeliveries="2" delay="5000"/&gt;
&lt;/onException&gt;</code></pre>
     </div>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_point_of_entry_for_redelivery_attempts">
   <a class="anchor" href="#_point_of_entry_for_redelivery_attempts">
   </a>
   Point of Entry for Redelivery Attempts
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     All redelivery attempts start at the point of the failure. So the route:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">onException(ConnectException.class)
    .from("direct:start")
    .process("processor1")
    .process("processor2") // &lt;--- throws a ConnectException
    .to("mock:theEnd")</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     Will retry from
     <strong>
      <code>
       processor2
      </code>
     </strong>
     - not the complete route.
    </p>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_reusing_redeliverypolicy">
   <a class="anchor" href="#_reusing_redeliverypolicy">
   </a>
   Reusing RedeliveryPolicy
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     You can reference a
     <strong>
      <code>
       RedeliveryPolicy
      </code>
     </strong>
     so you can reuse existing configurations and use standard spring bean style configuration that supports property placeholders.
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml">&lt;bean id="myRedeliveryPolicy" class="org.apache.camel.processor.RedeliveryPolicy"&gt;
    &lt;property name="maximumRedeliveries" value="${myprop.max}"/&gt;
&lt;/bean&gt;

&lt;!-- here we reference our redelivery policy defined above --&gt;
&lt;onException redeliveryPolicyRef="myRedeliveryPolicy"&gt;
    &lt;!-- you can define multiple exceptions just adding more exception elements as show below --&gt;
    &lt;exception&gt;com.mycompany.MyFirstException&lt;/exception&gt;
    &lt;exception&gt;com.mycompany.MySecondException&lt;/exception&gt;
&lt;/onException&gt;</code></pre>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_asynchronous_delayed_redelivery">
   <a class="anchor" href="#_asynchronous_delayed_redelivery">
   </a>
   Asynchronous Delayed Redelivery
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     Camel has a feature to
     <em>
      not block
     </em>
     while waiting for a delayed redelivery to occur. However if you use transacted routes then Camel will block as its mandated by the transaction manager to execute all the work in the same thread context. You can enable the non blocking asynchronous behavior by the
     <strong>
      <code>
       asyncDelayedRedelivery
      </code>
     </strong>
     option. This option can be set on the
     <strong>
      <code>
       errorHandler
      </code>
     </strong>
     ,
     <strong>
      <code>
       onException
      </code>
     </strong>
     or the redelivery policies.
    </p>
   </div>
   <div class="paragraph">
    <p>
     By default, the error handler will create and use a scheduled thread pool to trigger redelivery in the future. You can also configure the
     <strong>
      <code>
       executorServiceRef
      </code>
     </strong>
     on the
     <a class="xref page" href="error-handler.html">
      Error Handler
     </a>
     to indicate a reference to either a shared thread pool you can enlist in the registry, or a thread pool profile in case you want to be able to control pool settings.
    </p>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_catching_multiple_exceptions">
   <a class="anchor" href="#_catching_multiple_exceptions">
   </a>
   Catching Multiple Exceptions
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     Multiple exception can be caught as shown:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">onException(MyBusinessException.class, MyOtherBusinessException.class)
    .maximumRedeliveries(2)
    .to("activemq:businessFailed");</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     And in XML DSL you just add another exception element:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml">&lt;onException&gt;
    &lt;exception&gt;com.mycompany.MyBusinessException&lt;/exception&gt;
    &lt;exception&gt;com.mycompany.MyOtherBusinessException&lt;/exception&gt;
    &lt;redeliveryPolicy maximumRedeliveries="2"/&gt;
    &lt;to uri="activemq:businessFailed"/&gt;
&lt;/onException&gt;</code></pre>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_using_a_processor_as_a_failure_handler">
   <a class="anchor" href="#_using_a_processor_as_a_failure_handler">
   </a>
   Using a Processor as a Failure Handler
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     We want to handle certain exceptions in a specific way, so we add a
     <strong>
      <code>
       onException
      </code>
     </strong>
     clause for the particular exception.
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">// here we register exception cause for MyFunctionException
// when this exception occurs we want it to be processed by our
// processor
onException(MyFunctionalException.class)
  .process(new MyFunctionFailureHandler())
  .stop();</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     So what happens is that whenever a
     <strong>
      <code>
       MyFunctionalException
      </code>
     </strong>
     is thrown it is being routed to our processor
     <strong>
      <code>
       MyFunctionFailureHandler
      </code>
     </strong>
     . So you can say that the exchange is diverted when a
     <strong>
      <code>
       MyFunctionalException
      </code>
     </strong>
     is thrown during processing. It’s important to distinct this as perfectly valid. The default redelivery policy from the
     <a class="xref page" href="../components/4.10.x/eips/dead-letter-channel.html">
      Dead Letter Channel
     </a>
     will not kick in, so our processor receives the Exchange directly, without any redeliver attempted. In our processor we need to determine what to do. Camel regards the Exchange as
     <strong>
      failure handled
     </strong>
     . So our processor is the end of the route. So lets look the code for our processor.
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">    public static class MyFunctionFailureHandler implements Processor {

        @Override
        public void process(Exchange exchange) throws Exception {
            // the caused by exception is stored in a property on the exchange
            Throwable caused = exchange.getProperty(Exchange.EXCEPTION_CAUGHT, Throwable.class);
            assertNotNull(caused);
            // here you can do what you want, but Camel regards this exception as
            // handled, and this processor as a failure handler, so it won't do redeliveries.
            // So this is the end of this route.
        }
    }</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     Notice how we get the
     <strong>
      caused by
     </strong>
     exception using a property on the Exchange. This is where Camel stores any caught exception during processing. So you can fetch this property and check what the exception message and do what you want.
    </p>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_marking_exceptions_as_handled">
   <a class="anchor" href="#_marking_exceptions_as_handled">
   </a>
   Marking Exceptions as Handled
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     See also the section
     <a href="#_handle_and_continue_exceptions">
      Handle and Continue Exceptions
     </a>
     below.
    </p>
   </div>
   <div class="paragraph">
    <p>
     Using
     <strong>
      <code>
       onException
      </code>
     </strong>
     to handle known exceptions is a very powerful feature in Camel. You can mark the exception as being handled with the
     <strong>
      handle
     </strong>
     DSL, so the caller will not receive the caused exception as a response. The handle is a
     <a class="xref page" href="predicate.html">
      Predicate
     </a>
     that is overloaded to accept three types of parameters:
    </p>
   </div>
   <div class="ulist">
    <ul>
     <li>
      <p>
       Boolean
      </p>
     </li>
     <li>
      <p>
       <a class="xref page" href="predicate.html">
        Predicate
       </a>
      </p>
     </li>
     <li>
      <p>
       <a class="xref page" href="expression.html">
        Expression
       </a>
       that will be evaluated as a
       <a class="xref page" href="predicate.html">
        Predicate
       </a>
       using this rule set: If the expression returns a Boolean, it is used directly. For any other response, it is regarded as
       <code>
        true
       </code>
       if the response is
       <code>
        not null
       </code>
       .
      </p>
     </li>
    </ul>
   </div>
   <div class="paragraph">
    <p>
     For instance to mark all
     <strong>
      <code>
       ValidationException
      </code>
     </strong>
     as being handled we can do this:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">onException(ValidationException)
    .handled(true);</code></pre>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_example_using_handled">
   <a class="anchor" href="#_example_using_handled">
   </a>
   Example Using Handled
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     In this route below we want to do special handling of all
     <strong>
      <code>
       OrderFailedException
      </code>
     </strong>
     as we want to return a customized response to the caller. First we setup our routing as:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">    // we do special error handling for when OrderFailedException is
    // thrown
    onException(OrderFailedException.class)
        // we mark the exchange as handled so the caller doesn't
        // receive the
        // OrderFailedException but whatever we want to return
        // instead
        .handled(true)
        // this bean handles the error handling where we can
        // customize the error
        // response using java code
        .bean(OrderService.class, "orderFailed")
        // and since this is an unit test we use mocks for testing
        .to("mock:error");

    // this is just the generic error handler where we set the
    // destination
    // and the number of redeliveries we want to try
    errorHandler(deadLetterChannel("mock:error").maximumRedeliveries(1));

    // this is our route where we handle orders
    from("direct:start")
        // this bean is our order service
        .bean(OrderService.class, "handleOrder")
        // this is the destination if the order is OK
        .to("mock:result");</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     Then we have our service bean that is just a plain POJO demonstrating how you can use
     <a class="xref page" href="bean-integration.html">
      Bean Integration
     </a>
     in Camel to avoid being tied to the Camel API:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">    /**
     * Order service as a plain POJO class
     */
    public static class OrderService {

        /**
         * This method handle our order input and return the order
         */
        public Object handleOrder(@Headers Map headers, @Body String payload) throws OrderFailedException {
            headers.put("customerid", headers.get("customerid"));
            if ("Order: kaboom".equals(payload)) {
                throw new OrderFailedException("Cannot order: kaboom");
            } else {
                headers.put("orderid", "123");
                return "Order OK";
            }
        }

        /**
         * This method creates the response to the caller if the order could not
         * be processed
         */
        public Object orderFailed(@Headers Map headers, @Body String payload) {
            headers.put("customerid", headers.get("customerid"));
            headers.put("orderid", "failed");
            return "Order ERROR";
        }
    }</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     And finally the exception that is being thrown is just a regular exception:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">    public static class OrderFailedException extends Exception {

        private static final long serialVersionUID = 1L;

        public OrderFailedException(String message) {
            super(message);
        }

    }</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     So what happens?
    </p>
   </div>
   <div class="paragraph">
    <p>
     If we sent an order that is being processed OK then the caller will receive an Exchange as reply containing
     <strong>
      <code>
       Order OK
      </code>
     </strong>
     as the payload and
     <strong>
      <code>
       orderid=123
      </code>
     </strong>
     in a header.
    </p>
   </div>
   <div class="paragraph">
    <p>
     If the order could
     <strong>
      not
     </strong>
     be processed and thus an
     <strong>
      <code>
       OrderFailedException
      </code>
     </strong>
     was thrown the caller will
     <strong>
      not
     </strong>
     receive this exception but our customized response that we have fabricated in the
     <strong>
      <code>
       orderFailed
      </code>
     </strong>
     method in our
     <strong>
      <code>
       OrderService
      </code>
     </strong>
     . So the caller receives an Exchange with the payload
     <strong>
      <code>
       Order ERROR
      </code>
     </strong>
     and a
     <strong>
      <code>
       orderid=failed
      </code>
     </strong>
     in a header.
    </p>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_using_handled_with_spring_xml_dsl">
   <a class="anchor" href="#_using_handled_with_spring_xml_dsl">
   </a>
   Using Handled with Spring XML DSL
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     The same route as above in Spring XML DSL:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml"> &lt;!-- setup our error handler as the deal letter channel --&gt;
&lt;bean id="errorHandler" class="org.apache.camel.builder.DeadLetterChannelBuilder"&gt;
    &lt;property name="deadLetterUri" value="mock:error"/&gt;
&lt;/bean&gt;

&lt;!-- this is our POJO bean with our business logic defined as a plain spring bean --&gt;
&lt;bean id="orderService" class="org.apache.camel.spring.processor.onexception.OrderService" /&gt;

&lt;!-- this is the camel context where we define the routes --&gt;
&lt;!-- define our error handler as a global error handler --&gt;
&lt;camelContext errorHandlerRef="errorHandler" xmlns="http://camel.apache.org/schema/spring"&gt;

  &lt;onException&gt;
    &lt;!-- the exception is full qualified names as plain strings --&gt;
    &lt;!-- there can be more just add a 2nd, 3rd exception element (unbounded) --&gt;
    &lt;exception&gt;org.apache.camel.spring.processor.onexception.OrderFailedException&lt;/exception&gt;
    &lt;!-- we can set the redelivery policy here as well --&gt;
    &lt;redeliveryPolicy maximumRedeliveries="1" /&gt;
    &lt;!-- mark this as handled --&gt;
    &lt;handled&gt;
      &lt;constant&gt;true&lt;/constant&gt;
    &lt;/handled&gt;
    &lt;!-- let our order service handle this exception, call the orderFailed method --&gt;
    &lt;bean ref="orderService" method="orderFailed" /&gt;
    &lt;!-- and since this is a unit test we use mock for assertions --&gt;
    &lt;to uri="mock:error" /&gt;
  &lt;/onException&gt;

  &lt;route&gt;
    &lt;!-- the route --&gt;
    &lt;from uri="direct:start" /&gt;
    &lt;!-- in the normal route then route to our order service and call handleOrder method --&gt;
    &lt;bean ref="orderService" method="handleOrder" /&gt;
    &lt;!-- and since this is a unit test we use mock for assertions --&gt;
    &lt;to uri="mock:result" /&gt;
  &lt;/route&gt;

&lt;/camelContext&gt;</code></pre>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_handling_and_sending_a_fixed_response_back_to_the_client">
   <a class="anchor" href="#_handling_and_sending_a_fixed_response_back_to_the_client">
   </a>
   Handling and Sending a Fixed Response Back to the Client
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     In the route above we handled the exception but routed it to a different endpoint. What if you need to alter the response and send a fixed response back to the original caller (the client). No secret here just do as you do in normal Camel routing, use
     <a class="xref page" href="../components/4.10.x/eips/message-translator.html">
      transform
     </a>
     to set the response, as shown in the sample below:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">// we catch MyFunctionalException and want to mark it as handled
// (= no failure returned to client)
// but we want to return a fixed text response, so we transform
// OUT body as Sorry.
onException(MyFunctionalException.class)
  .handled(true)
  .transform().constant("Sorry");</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     We modify the sample slightly to return the original caused exception message instead of the fixed text
     <code>
      Sorry
     </code>
     :
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">// we catch MyFunctionalException and want to mark it as handled
// (= no failure returned to client)
// but we want to return a fixed text response, so we transform
// OUT body and return the exception message
onException(MyFunctionalException.class)
  .handled(true)
  .transform(exceptionMessage());</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     And we can use the
     <a class="xref page" href="../components/4.10.x/languages/simple-language.html">
      Simple
     </a>
     language to set a readable error message with the caused exception message:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">// we catch MyFunctionalException and want to mark it as handled
// (= no failure returned to client)
// but we want to return a fixed text response, so we transform
// OUT body and return a nice message
// using the simple language where we want insert the exception
// message
onException(MyFunctionalException.class)
  .handled(true)
  .transform().simple("Error reported: ${exception.message} - cannot process this message.");</code></pre>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_handle_and_continue_exceptions">
   <a class="anchor" href="#_handle_and_continue_exceptions">
   </a>
   Handle and Continue Exceptions
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     The option
     <code>
      continued
     </code>
     allows you to both
     <strong>
      <code>
       handle
      </code>
     </strong>
     and
     <strong>
      <code>
       continue
      </code>
     </strong>
     routing in the original route as if the exception did not occur.
    </p>
   </div>
   <div class="paragraph">
    <p>
     For example: to ignore and continue when the
     <strong>
      <code>
       IDontCareException
      </code>
     </strong>
     was thrown we can do this:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">onException(IDontCareException.class)
    .continued(true);</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     You can maybe compare continued with a having a
     <strong>
      <code>
       try …​ catch
      </code>
     </strong>
     block around each step and then just ignore the exception. Using continued makes it easier in Camel as you otherwise had to use
     <a class="xref page" href="try-catch-finally.html">
      Try Catch Finally
     </a>
     style for this kind of use case.
    </p>
   </div>
   <div class="sect2">
    <h3 id="_example_using_continued">
     <a class="anchor" href="#_example_using_continued">
     </a>
     Example Using continued
    </h3>
    <div class="paragraph">
     <p>
      In this route below we want to do special handling of all
      <strong>
       <code>
        IllegalArgumentException
       </code>
      </strong>
      as we just want to continue routing.
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">onException(IllegalArgumentException.class).continued(true);

from("direct:start")
  .to("mock:start")
  .throwException(new IllegalArgumentException("Forced"))
  .to("mock:result");</code></pre>
     </div>
    </div>
    <div class="paragraph">
     <p>
      And the same example in Spring XML DSL:
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml"> &lt;camelContext xmlns="http://camel.apache.org/schema/spring"&gt;

        &lt;onException&gt;
            &lt;exception&gt;java.lang.IllegalArgumentException&lt;/exception&gt;
            &lt;!-- tell Camel to handle and continue when this exception was thrown --&gt;
            &lt;continued&gt;&lt;constant&gt;true&lt;/constant&gt;&lt;/continued&gt;
        &lt;/onException&gt;

        &lt;route&gt;
            &lt;from uri="direct:start"/&gt;
            &lt;to uri="mock:start"/&gt;
            &lt;throwException message="Forced" exceptionType="java.lang.IllegalArgumentException"/&gt;
            &lt;to uri="mock:result"/&gt;
        &lt;/route&gt;

    &lt;/camelContext&gt;</code></pre>
     </div>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_what_is_the_difference_between_handled_and_continued">
   <a class="anchor" href="#_what_is_the_difference_between_handled_and_continued">
   </a>
   What is the Difference Between Handled and Continued?
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     If handled is true, then the thrown exception will be
     <em>
      handled
     </em>
     and Camel will
     <strong>
      not
     </strong>
     continue routing in the original route, but break out. However you can configure a route in the
     <strong>
      <code>
       onException
      </code>
     </strong>
     which will be used instead. You use this route if you need to create some custom response message back to the caller, or do any other processing because that exception was thrown.
    </p>
   </div>
   <div class="paragraph">
    <p>
     If continued is true, then Camel will catch the exception and in fact just ignore it and continue routing in the original route. However if you have a route configured in the
     <strong>
      <code>
       onException
      </code>
     </strong>
     it will route that route first, before it will continue routing in the original route.
    </p>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_using_useoriginalmessage">
   <a class="anchor" href="#_using_useoriginalmessage">
   </a>
   Using
   <code>
    useOriginalMessage
   </code>
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     The option
     <strong>
      <code>
       useOriginalMessage
      </code>
     </strong>
     is used for routing the original input message instead of the current message that potential is modified during routing.
    </p>
   </div>
   <div class="paragraph">
    <p>
     For example: if you have this route:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">from("jms:queue:order:input")
    .to("bean:validateOrder");
    .to("bean:transformOrder")
    .to("bean:handleOrder");</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     The route listen for JMS messages and validates, transforms and handle it. During this the
     <a class="xref page" href="exchange.html">
      Exchange
     </a>
     payload is transformed/modified. So in case something goes wrong and we want to move the message to another JMS destination, then we can add an
     <strong>
      <code>
       onException
      </code>
     </strong>
     . But when we move the
     <a class="xref page" href="exchange.html">
      Exchange
     </a>
     to this destination we do not know in which state the message is in. Did the error happen in before the
     <strong>
      <code>
       transformOrder
      </code>
     </strong>
     or after? So to be sure we want to move the original input message we received from
     <code>
      jms:queue:order:input
     </code>
     . So we can do this by enabling the
     <strong>
      <code>
       useOriginalMessage
      </code>
     </strong>
     option as shown below:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">// will use original input message (body and headers)
onException(MyOrderException.class)
    .useOriginalMessage()
    .handled(true)
    .to("jms:queue:order:failed");</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     Then the messages routed to the
     <strong>
      <code>
       jms:queue:order:failed
      </code>
     </strong>
     is the original input. If we want to manually retry we can move the JMS message from the failed to the input queue, with no problem as the message is the same as the original we received.
    </p>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_useoriginalmessage_with_spring_dsl">
   <a class="anchor" href="#_useoriginalmessage_with_spring_dsl">
   </a>
   <code>
    useOriginalMessage
   </code>
   with Spring DSL
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     The
     <strong>
      <code>
       useOriginalMessage
      </code>
     </strong>
     option is defined as a boolean attribute on the
     <strong>
      <code>
       &lt;onException&gt;
      </code>
     </strong>
     XML tag in Spring DSL. So the definition above would be:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml">&lt;onException useOriginalMessage="true"&gt;
    &lt;exception&gt;com.mycompany.MyOrderException&lt;/exception&gt;
    &lt;handled&gt;&lt;constant&gt;true&lt;/constant&gt;&lt;/handled&gt;
    &lt;to uri="jms:queue:order:failed"/&gt;
&lt;/onException&gt;</code></pre>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_boundary_of_original_message">
   <a class="anchor" href="#_boundary_of_original_message">
   </a>
   Boundary of original message
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     The original input means the input message that are bounded by the current unit of work. An unit of work typically spans one route, or multiple routes if they are connected using internal endpoints such as direct or seda. When messages are passed via external endpoints such as JMS or HTTP then the consumer will create a new unit of work, with the message it received as input as the original input. Also, some EIP patterns such as splitter, multicast, will create a new unit of work boundary for the messages in their sub-route (i.e. the split message); however these EIPs have an option named shareUnitOfWork which allows combining with the parent unit of work in regard to error handling and therefore use the parent original message.
    </p>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_using_useoriginalbody">
   <a class="anchor" href="#_using_useoriginalbody">
   </a>
   Using
   <code>
    useOriginalBody
   </code>
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     The useOriginalBody is similar to useOriginalMessage as documented above. You may want to use useOriginalBody when you want to be able to enrich the message with custom headers and preserve the original message body before sending to an error handler or dead letter channel.
    </p>
   </div>
   <div class="paragraph">
    <p>
     For example: if you have this route:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">// will use original input body
onException(MyOrderException.class)
    .useOriginalBody()
    .handled(true)
    .to("jms:queue:order:failed");

from("jms:queue:order:input")
    .setHeader("application", constant("OrderApp"))
    .to("bean:validateOrder");
    .to("bean:transformOrder")
    .to("bean:handleOrder");</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     Then the message has been enriched with a header named application after the original message was received by the JMS endpoint. And in case of an error
     <code>
      onException
     </code>
     will handle the exception and use the original message body and the headers from the current message as-is, which means the headers will include the application header.
    </p>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_advanced_usage_of_exception_clause">
   <a class="anchor" href="#_advanced_usage_of_exception_clause">
   </a>
   Advanced Usage of Exception Clause
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     Camel supports advanced configuration of exception clauses.
    </p>
   </div>
   <div class="sect2">
    <h3 id="_using_global_and_per_route_exception_clauses">
     <a class="anchor" href="#_using_global_and_per_route_exception_clauses">
     </a>
     Using Global and Per Route Exception Clauses
    </h3>
    <div class="paragraph">
     <p>
      You can define exception clauses either as:
     </p>
    </div>
    <div class="ulist">
     <ul>
      <li>
       <p>
        global
       </p>
      </li>
      <li>
       <p>
        or route specific
       </p>
      </li>
     </ul>
    </div>
    <div class="paragraph">
     <p>
      We start off with the sample that we change over time. First off we use only global exception clauses:
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">// default should errors go to mock:error
errorHandler(deadLetterChannel("mock:error").redeliveryDelay(0));

// if a MyTechnicalException is thrown we will not try to
// redeliver and we mark it as handled
// so the caller does not get a failure
// since we have no to then the exchange will continue to be
// routed to the normal error handler
// destination that is mock:error as defined above
onException(MyTechnicalException.class).maximumRedeliveries(0).handled(true);

// if a MyFunctionalException is thrown we do not want Camel to
// redelivery but handle it our self using
// our bean myOwnHandler, then the exchange is not routed to the
// default error (mock:error)
onException(MyFunctionalException.class).maximumRedeliveries(0).handled(true).to("bean:myOwnHandler");

// here we route message to our service bean
from("direct:start").choice().when().xpath("//type = 'myType'").to("bean:myServiceBean").end().to("mock:result");</code></pre>
     </div>
    </div>
    <div class="paragraph">
     <p>
      In the next sample we change the global exception policies to be pure route specific.
     </p>
    </div>
   </div>
   <div class="sect2">
    <h3 id="_must_use_end_for_route_specific_exception_policies">
     <a class="anchor" href="#_must_use_end_for_route_specific_exception_policies">
     </a>
     Must use
     <code>
      .end()
     </code>
     for route specific exception policies
    </h3>
    <div class="paragraph">
     <p>
      [IMPORTANT] This requires to end the
      <strong>
       <code>
        onException
       </code>
      </strong>
      route with
      <strong>
       <code>
        .end()
       </code>
      </strong>
      to indicate where it stops and when the regular route continues.
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">// default should errors go to mock:error
errorHandler(deadLetterChannel("mock:error"));

// here we start the routing with the consumer
from("direct:start")

    // if a MyTechnicalException is thrown we will not try to
    // redeliver and we mark it as handled
    // so the caller does not get a failure
    // since we have no to then the exchange will continue to be
    // routed to the normal error handler
    // destination that is mock:error as defined above
    // we MUST use .end() to indicate that this sub block is
    // ended
    .onException(MyTechnicalException.class).maximumRedeliveries(0).handled(true).end()

    // if a MyFunctionalException is thrown we do not want Camel
    // to redelivery but handle it our self using
    // our bean myOwnHandler, then the exchange is not routed to
    // the default error (mock:error)
    // we MUST use .end() to indicate that this sub block is
    // ended
    .onException(MyFunctionalException.class).maximumRedeliveries(0).handled(true).to("bean:myOwnHandler").end()

    // here we have the regular routing
    .choice().when().xpath("//type = 'myType'").to("bean:myServiceBean").end().to("mock:result");</code></pre>
     </div>
    </div>
    <div class="paragraph">
     <p>
      And now it gets complex as we combine global and route specific exception policies as we introduce a second route in the sample:
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">// global error handler
// as its based on a unit test we do not have any delays between
// and do not log the stack trace
errorHandler(deadLetterChannel("mock:error").redeliveryDelay(0).logStackTrace(false));

// shared for both routes
onException(MyTechnicalException.class).handled(true).maximumRedeliveries(2).to("mock:tech.error");

from("direct:start")
    // route specific on exception for MyFunctionalException
    // we MUST use .end() to indicate that this sub block is
    // ended
    .onException(MyFunctionalException.class).maximumRedeliveries(0).end().to("bean:myServiceBean").to("mock:result");

from("direct:start2")
    // route specific on exception for MyFunctionalException
    // that is different than the previous route
    // here we marked it as handled and send it to a different
    // destination mock:handled
    // we MUST use .end() to indicate that this sub block is
    // ended
    .onException(MyFunctionalException.class).handled(true).maximumRedeliveries(0).to("mock:handled").end().to("bean:myServiceBean").to("mock:result");</code></pre>
     </div>
    </div>
    <div class="paragraph">
     <p>
      Notice that we can define the same exception
      <strong>
       <code>
        MyFunctionalException
       </code>
      </strong>
      in both routes, but they are configured differently and thus is handled different depending on the route. You can of course also add a new
      <strong>
       <code>
        onException
       </code>
      </strong>
      to one of the routes so it has an additional exception policy.
     </p>
    </div>
    <div class="paragraph">
     <p>
      And finally we top this by throwing in a nested error handler as well, as we add the 3rd route shown below:
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">from("direct:start3")
    // route specific error handler that is different than the
    // global error handler
    // here we do not redeliver and send errors to mock:error3
    // instead of the global endpoint
    .errorHandler(deadLetterChannel("mock:error3").maximumRedeliveries(0))

    // route specific on exception to mark MyFunctionalException
    // as being handled
    .onException(MyFunctionalException.class).handled(true).end()
    // however we want the IO exceptions to redeliver at most 3
    // times
    .onException(IOException.class).maximumRedeliveries(3).end().to("bean:myServiceBean").to("mock:result");</code></pre>
     </div>
    </div>
   </div>
   <div class="sect2">
    <h3 id="_global_exception_policies_and_nested_error_handlers">
     <a class="anchor" href="#_global_exception_policies_and_nested_error_handlers">
     </a>
     Global exception policies and nested error handlers
    </h3>
    <div class="paragraph">
     <p>
      The sample above with both nested error handlers and both global and per route exception clauses is a bit advanced. It’s important to get the fact straight that the
      <strong>
       global
      </strong>
      exception clauses is really global so they also applies for nested error handlers. So if a
      <strong>
       <code>
        MyTechnicalException
       </code>
      </strong>
      is thrown then it’s the global exception policy that is selected.
     </p>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_using_fine_grained_selection_using_onwhen_predicate">
   <a class="anchor" href="#_using_fine_grained_selection_using_onwhen_predicate">
   </a>
   Using Fine Grained Selection Using
   <code>
    onWhen
   </code>
   Predicate
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     You can attach an
     <a class="xref page" href="expression.html">
      Expression
     </a>
     to the exception clause to have fine grained control when a clause should be selected or not. As it’s an
     <a class="xref page" href="expression.html">
      Expression
     </a>
     you can use any kind of code to perform the test. Here is a sample:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">errorHandler(deadLetterChannel("mock:error").redeliveryDelay(0).maximumRedeliveries(3));

// here we define our onException to catch MyUserException when
// there is a header[user] on the exchange that is not null
onException(MyUserException.class).onWhen(header("user").isNotNull()).maximumRedeliveries(1)
    // setting delay to zero is just to make unit testing faster
    .redeliveryDelay(0).to(ERROR_USER_QUEUE);

// here we define onException to catch MyUserException as a kind
// of fallback when the above did not match.
// Notice: The order how we have defined these onException is
// important as Camel will resolve in the same order as they
// have been defined
onException(MyUserException.class).maximumRedeliveries(2)
    // setting delay to zero is just to make unit testing faster
    .redeliveryDelay(0).to(ERROR_QUEUE);</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     In the sample above we have two
     <strong>
      <code>
       onException
      </code>
     </strong>
     's defined. The first has an
     <strong>
      <code>
       onWhen
      </code>
     </strong>
     expression attached to only trigger if the message has a header with the key user that is not null. If so this clause is selected and is handling the thrown exception. The second clause is a for coarse gained selection to select the same exception being thrown but when the expression is evaluated to false.
    </p>
   </div>
   <div class="admonitionblock note">
    <div class="table-wrapper">
     <table>
      <tr>
       <td class="icon">
        <i class="fa icon-note" title="Note">
        </i>
       </td>
       <td class="content">
        <div class="paragraph">
         <p>
          This is not required, if the second clause is omitted, then the default error handler will kick in.
         </p>
        </div>
       </td>
      </tr>
     </table>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_using_onredelivery_processor">
   <a class="anchor" href="#_using_onredelivery_processor">
   </a>
   Using onRedelivery Processor
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     <a class="xref page" href="../components/4.10.x/eips/dead-letter-channel.html">
      Dead Letter Channel
     </a>
     has support for
     <strong>
      <code>
       onRedelivery
      </code>
     </strong>
     to allow custom processing of a Message before its being redelivered. It can be used to add some customer header or whatnot. In Camel 2.0 we have added this feature to
     <a href="#">
      Exception Clause
     </a>
     as well, so you can use per exception scoped on redelivery. Camel will fallback to use the one defined on
     <a class="xref page" href="../components/4.10.x/eips/dead-letter-channel.html">
      Dead Letter Channel
     </a>
     if any, if none exists on the
     <a href="#">
      Exception Clause
     </a>
     . See
     <a class="xref page" href="../components/4.10.x/eips/dead-letter-channel.html">
      Dead Letter Channel
     </a>
     for more details on
     <strong>
      <code>
       onRedelivery
      </code>
     </strong>
     .
    </p>
   </div>
   <div class="paragraph">
    <p>
     In the code below we want to do some custom code before redelivering any
     <strong>
      <code>
       IOException
      </code>
     </strong>
     . So we configure an
     <strong>
      <code>
       onException
      </code>
     </strong>
     for the
     <strong>
      <code>
       IOException
      </code>
     </strong>
     and set the
     <strong>
      <code>
       onRedelivery
      </code>
     </strong>
     to use our custom processor:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">// when we redeliver caused by an IOException we want to do some
// special code before the redeliver attempt
onException(IOException.class)
    // try to redeliver at most 3 times
    .maximumRedeliveries(3)
    // setting delay to zero is just to make unit testing faster
    .redeliveryDelay(0).onRedelivery(new MyIORedeliverProcessor());</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     And in our custom processor we set a special timeout header to the message. You can of course do anything what you like in your code.
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">// This is our processor that is executed before every redelivery attempt
// here we can do what we want in the java code, such as altering the
// message
public static class MyRedeliverProcessor implements Processor {

    @Override
    public void process(Exchange exchange) throws Exception {
        // the message is being redelivered so we can alter it

        // we just append the redelivery counter to the body
        // you can of course do all kind of stuff instead
        String body = exchange.getIn().getBody(String.class);
        int count = exchange.getIn().getHeader("CamelRedeliveryCounter", Integer.class);

        exchange.getIn().setBody(body + count);
    }
}</code></pre>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_using_onredelivery_in_spring_xml_dsl">
   <a class="anchor" href="#_using_onredelivery_in_spring_xml_dsl">
   </a>
   Using onRedelivery in Spring XML DSL
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     In Spring DSL you need to use the
     <strong>
      <code>
       onRedeliveryRef
      </code>
     </strong>
     attribute to refer to a spring bean id that is your custom processor:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml">&lt;onException onRedeliveryRef="myIORedeliverProcessor"&gt;
    &lt;exception&gt;java.io.IOException&lt;/exception&gt;
&lt;/onException&gt;</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     And our processor is just a regular spring bean (we use
     <strong>
      <code>
       $
      </code>
     </strong>
     for the inner class as this code is based on unit testing):
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml"> &lt;bean id="myRedeliveryProcessor"
          class="org.apache.camel.processor.DeadLetterChannelOnExceptionOnRedeliveryTest$MyRedeliverProcessor"/&gt;</code></pre>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_using_onexceptionoccurred_processor">
   <a class="anchor" href="#_using_onexceptionoccurred_processor">
   </a>
   Using onExceptionOccurred Processor
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     <a class="xref page" href="../components/4.10.x/eips/dead-letter-channel.html">
      Dead Letter Channel
     </a>
     has support for
     <strong>
      <code>
       onExceptionOccurred
      </code>
     </strong>
     to allow custom processing of a Message just after the exception was thrown. It can be used to do some custom logging or whatnot. The difference between
     <strong>
      <code>
       onRedelivery
      </code>
     </strong>
     processor and
     <strong>
      <code>
       onExceptionOccurred
      </code>
     </strong>
     processor, is that the former is processed just before a redelivery attempt is being performed, that means it will not happen right after an exception was thrown. For example if the error handler has been configured to perform 5 seconds delay between redelivery attempts, then the redelivery processor is invoked 5 seconds after the exception was thrown. On the other hand the
     <strong>
      <code>
       onExceptionOccurred
      </code>
     </strong>
     processor is always invoked right after the exception was thrown, and also if redelivery has been disabled.
    </p>
   </div>
   <div class="admonitionblock note">
    <div class="table-wrapper">
     <table>
      <tr>
       <td class="icon">
        <i class="fa icon-note" title="Note">
        </i>
       </td>
       <td class="content">
        <div class="paragraph">
         <p>
          Any new exceptions thrown from the
          <strong>
           <code>
            onExceptionOccurred
           </code>
          </strong>
          processor is logged as
          <strong>
           <code>
            WARN
           </code>
          </strong>
          and ignored, to not override the existing exception.
         </p>
        </div>
       </td>
      </tr>
     </table>
    </div>
   </div>
   <div class="paragraph">
    <p>
     In the code below we want to do some custom logging when an exception happened. Therefore we configure an
     <strong>
      <code>
       onExceptionOccurred
      </code>
     </strong>
     to use our custom processor:
    </p>
   </div>
   <div class="listingblock java">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-none hljs">errorHandler(defaultErrorHandler()
    .maximumRedeliveries(3)
    .redeliveryDelay(5000)
    .onExceptionOccurred(myProcessor));</code></pre>
    </div>
   </div>
   <div class="sect2">
    <h3 id="_using_onredelivery_in_spring_xml_dsl_2">
     <a class="anchor" href="#_using_onredelivery_in_spring_xml_dsl_2">
     </a>
     Using onRedelivery in Spring XML DSL
    </h3>
    <div class="paragraph">
     <p>
      In Spring DSL you need to use the
      <strong>
       <code>
        onExceptionOccurredRef
       </code>
      </strong>
      attribute to refer to a spring bean id that is your custom processor:
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml">&lt;bean id="myProcessor" class="com.foo.MyExceptionLoggingProcessor"/&gt;

&lt;camelContext errorHandlerRef="eh" xmlns="http://camel.apache.org/schema/spring"&gt;
    &lt;errorHandler id="eh" type="DefaultErrorHandler" onExceptionOccurredRef="myProcessor"&gt;
        &lt;redeliveryPolicy maximumRedeliveries="3" redeliveryDelay="5000"/&gt;
    &lt;/errorHandler&gt;
    ...
&lt;/camelContext&gt;</code></pre>
     </div>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_using_fine_grained_retry_using_retrywhile_predicate">
   <a class="anchor" href="#_using_fine_grained_retry_using_retrywhile_predicate">
   </a>
   Using Fine Grained Retry Using retryWhile Predicate
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     When you need fine grained control for determining if an exchange should be retried or not you can use the
     <strong>
      <code>
       retryWhile
      </code>
     </strong>
     predicate. Camel will redeliver until the predicate returns false.
    </p>
   </div>
   <div class="paragraph">
    <p>
     Example:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">// we want to use a predicate for retries so we can determine in
// our bean when retry should stop, notice it will overrule the global
// error handler where we defined at most 1 redelivery attempt. Here we will
// continue until the predicate returns false
onException(MyFunctionalException.class).retryWhile(method("myRetryHandler")).handled(true).transform().constant("Sorry");</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     Where the bean
     <strong>
      <code>
       myRetryHandler
      </code>
     </strong>
     is computing if we should retry or not:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">public class MyRetryBean {

    // using bean binding we can bind the information from the exchange to
    // the types we have in our method signature
    public boolean retry(@Header(Exchange.REDELIVERY_COUNTER) Integer counter) {
        // NOTE: counter is the redelivery attempt, will start from 1
        // we can of course do what ever we want to determine the result but
        // this is a unit test so we end after 3 attempts
        return counter &lt; 3;
    }
}</code></pre>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_using_custom_exceptionpolicystrategy">
   <a class="anchor" href="#_using_custom_exceptionpolicystrategy">
   </a>
   Using Custom ExceptionPolicyStrategy
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     The default
     <a href="https://www.javadoc.io/doc/org.apache.camel/camel-core-processor/current/org/apache/camel/processor/errorhandler/ExceptionPolicyStrategy.html">
      ExceptionPolicyStrategy
     </a>
     in Camel should be sufficient in nearly all use-cases. However, if you need to use your own (use only for rare and advanced use-cases) this can be configured as the sample below illustrates:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">// configure the error handler to use my policy instead of the default from Camel
errorHandler(deadLetterChannel("mock:error").exceptionPolicyStrategy(new MyPolicy()));</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     Using our own strategy
     <strong>
      <code>
       MyPolicy
      </code>
     </strong>
     we can change the default behavior of Camel with our own code to resolve which exception type from above should be handling the given thrown exception.
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">public static class MyPolicy implements ExceptionPolicyStrategy {

    @Override
    public ExceptionPolicyKey getExceptionPolicy(Set&lt;ExceptionPolicyKey&gt; exceptionPolicies, Exchange exchange, Throwable exception) {
        // This is just an example that always forces the exception type configured
        // with MyPolicyException to win.
        return new ExceptionPolicyKey(null, MyPolicyException.class, null);
    }
}</code></pre>
    </div>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_using_the_exception_clause_in_spring_xml_dsl">
   <a class="anchor" href="#_using_the_exception_clause_in_spring_xml_dsl">
   </a>
   Using the Exception Clause in Spring XML DSL
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     You can use all of the above mentioned exception clause features in the Spring XML DSL as well. Here are a few examples:
    </p>
   </div>
   <div class="ulist">
    <ul>
     <li>
      <p>
       Global scoped
      </p>
     </li>
    </ul>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml">&lt;!-- setup our error handler as the deal letter channel --&gt;
&lt;bean id="errorHandler" class="org.apache.camel.builder.DeadLetterChannelBuilder"&gt;
    &lt;property name="deadLetterUri" value="mock:error"/&gt;
&lt;/bean&gt;

&lt;!-- this is our POJO bean with our business logic defined as a plain spring bean --&gt;
&lt;bean id="orderService" class="org.apache.camel.spring.processor.onexception.OrderService" /&gt;

&lt;!-- this is the camel context where we define the routes --&gt;
&lt;!-- define our error handler as a global error handler --&gt;
&lt;camelContext errorHandlerRef="errorHandler" xmlns="http://camel.apache.org/schema/spring"&gt;

  &lt;onException&gt;
    &lt;!-- the exception is full qualified names as plain strings --&gt;
    &lt;!-- there can be more just add a 2nd, 3rd exception element (unbounded) --&gt;
    &lt;exception&gt;org.apache.camel.spring.processor.onexception.OrderFailedException&lt;/exception&gt;
    &lt;!-- we can set the redelivery policy here as well --&gt;
    &lt;redeliveryPolicy maximumRedeliveries="1" /&gt;
    &lt;!-- mark this as handled --&gt;
    &lt;handled&gt;
      &lt;constant&gt;true&lt;/constant&gt;
    &lt;/handled&gt;
    &lt;!-- let our order service handle this exception, call the orderFailed method --&gt;
    &lt;bean ref="orderService" method="orderFailed" /&gt;
    &lt;!-- and since this is a unit test we use mock for assertions --&gt;
    &lt;to uri="mock:error" /&gt;
  &lt;/onException&gt;

  &lt;route&gt;
    &lt;!-- the route --&gt;
    &lt;from uri="direct:start" /&gt;
    &lt;!-- in the normal route then route to our order service and call handleOrder method --&gt;
    &lt;bean ref="orderService" method="handleOrder" /&gt;
    &lt;!-- and since this is a unit test we use mock for assertions --&gt;
    &lt;to uri="mock:result" /&gt;
  &lt;/route&gt;

&lt;/camelContext&gt;</code></pre>
    </div>
   </div>
   <div class="ulist">
    <ul>
     <li>
      <p>
       Route specific scoped
      </p>
     </li>
    </ul>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml">&lt;!-- setup our error handler as the deal letter channel --&gt;
&lt;bean id="deadLetter" class="org.apache.camel.builder.DeadLetterChannelBuilder"&gt;
    &lt;property name="deadLetterUri" value="mock:dead"/&gt;
&lt;/bean&gt;

&lt;!-- the default error handler used in the 2nd route --&gt;
&lt;bean id="defaultErrorHandler" class="org.apache.camel.builder.DefaultErrorHandlerBuilder"/&gt;

&lt;!-- this is our POJO bean with our business logic defined as a plain spring bean --&gt;
&lt;bean id="orderService" class="org.apache.camel.spring.processor.onexception.OrderService"/&gt;

&lt;!-- this is the camel context where we define the routes --&gt;
&lt;camelContext xmlns="http://camel.apache.org/schema/spring"&gt;

    &lt;route errorHandlerRef="deadLetter"&gt;
        &lt;from uri="direct:start"/&gt;
        &lt;onException&gt;
            &lt;exception&gt;org.apache.camel.spring.processor.onexception.OrderFailedException&lt;/exception&gt;
            &lt;redeliveryPolicy maximumRedeliveries="1"/&gt;
            &lt;handled&gt;
                &lt;constant&gt;true&lt;/constant&gt;
            &lt;/handled&gt;
            &lt;bean ref="orderService" method="orderFailed"/&gt;
            &lt;to uri="mock:error"/&gt;
        &lt;/onException&gt;
        &lt;bean ref="orderService" method="handleOrder"/&gt;
        &lt;to uri="mock:result"/&gt;
    &lt;/route&gt;

    &lt;!-- The exception clause specified in the first route will not be used in this route --&gt;
    &lt;route errorHandlerRef="defaultErrorHandler"&gt;
        &lt;from uri="direct:start_with_no_handler"/&gt;
        &lt;bean ref="orderService" method="handleOrder"/&gt;
        &lt;to uri="mock:result"/&gt;
    &lt;/route&gt;

&lt;/camelContext&gt;</code></pre>
    </div>
   </div>
  </div>
 </div>
</article>
