<article class="doc">
 <h1 class="page">
  Try, Catch and Finally
 </h1>
 <div id="preamble">
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     Camel supports the Java equivalent of try …​ catch …​ finally directly in the DSL. It aims to work like its Java sisters but with more power.
    </p>
   </div>
   <div class="paragraph">
    <p>
     In Camel, we prefix the keywords with
     <code>
      do
     </code>
     to avoid having same keyword as Java. So we have:
    </p>
   </div>
   <div class="ulist">
    <ul>
     <li>
      <p>
       <code>
        doTry
       </code>
      </p>
     </li>
     <li>
      <p>
       <code>
        doCatch
       </code>
      </p>
     </li>
     <li>
      <p>
       <code>
        doFinally
       </code>
      </p>
     </li>
     <li>
      <p>
       <code>
        end
       </code>
       to end the block in Java DSL
      </p>
     </li>
    </ul>
   </div>
   <div class="paragraph">
    <p>
     When using
     <code>
      doTry …​ doCatch …​ doFinally
     </code>
     then the regular Camel
     <a class="xref page" href="error-handler.html">
      Error Handler
     </a>
     is not in use; meaning any
     <code>
      onException
     </code>
     or the likes does not trigger. The reason is that
     <code>
      doTry …​ doCatch …​ doFinally
     </code>
     is in fact its own error handler and mimics how try/catch/finally works in Java.
    </p>
   </div>
  </div>
 </div>
 <div class="sect1">
  <h2 id="_using_dotry_docatch_dofinally">
   <a class="anchor" href="#_using_dotry_docatch_dofinally">
   </a>
   Using doTry …​ doCatch …​ doFinally
  </h2>
  <div class="sectionbody">
   <div class="paragraph">
    <p>
     In the route below we have all of them in action:
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">from("direct:start")
    .doTry()
        .process(new ProcessorFail())
        .to("mock:result")
    .doCatch(IOException.class, IllegalStateException.class)
        .to("mock:catch")
    .doFinally()
        .to("mock:finally")
    .end();</code></pre>
    </div>
   </div>
   <div class="paragraph">
    <p>
     And in XML DSL
    </p>
   </div>
   <div class="listingblock">
    <div class="content">
     <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml">&lt;route&gt;
  &lt;from uri="direct:start"/&gt;
  &lt;doTry&gt;
    &lt;process ref="processorFail"/&gt;
    &lt;to uri="mock:result"/&gt;
    &lt;doCatch&gt;
      &lt;exception&gt;java.io.IOException&lt;/exception&gt;
      &lt;exception&gt;java.lang.IllegalStateException&lt;/exception&gt;
      &lt;to uri="mock:catch"/&gt;
    &lt;/doCatch&gt;
    &lt;doFinally&gt;
       &lt;to uri="mock:finally"/&gt;
    &lt;/doFinally&gt;
  &lt;/doTry&gt;
&lt;/route&gt;</code></pre>
    </div>
   </div>
   <div class="sect2">
    <h3 id="_using_onwhen_with_docatch">
     <a class="anchor" href="#_using_onwhen_with_docatch">
     </a>
     Using onWhen with doCatch
    </h3>
    <div class="paragraph">
     <p>
      You can use
      <a class="xref page" href="predicate.html">
       Predicate
      </a>
      s with
      <code>
       doCatch
      </code>
      to make it runtime determine if the block should be triggered or not. In our case, we only want to trigger if the caused exception message contains the
      <strong>
       damn
      </strong>
      word.
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">from("direct:start")
    .doTry()
        .process(new ProcessorFail())
        .to("mock:result")
    .doCatch(IOException.class, IllegalStateException.class).onWhen(exceptionMessage().contains("Damn"))
        .to("mock:catch")
    .doCatch(CamelExchangeException.class)
        .to("mock:catchCamel")
    .doFinally()
        .to("mock:finally")
    .end();</code></pre>
     </div>
    </div>
    <div class="paragraph">
     <p>
      And in XML DSL
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml">&lt;route&gt;
  &lt;from uri="direct:start"/&gt;
  &lt;doTry&gt;
    &lt;process ref="processorFail"/&gt;
    &lt;to uri="mock:result"/&gt;
    &lt;doCatch&gt;
      &lt;exception&gt;java.io.IOException&lt;/exception&gt;
      &lt;exception&gt;java.lang.IllegalStateException&lt;/exception&gt;
      &lt;onWhen&gt;
        &lt;simple&gt;${exception.message} contains 'Damn'&lt;/simple&gt;
      &lt;/onWhen&gt;
      &lt;to uri="mock:catch"/&gt;
    &lt;/doCatch&gt;
    &lt;doCatch&gt;
      &lt;exception&gt;org.apache.camel.CamelExchangeException&lt;/exception&gt;
      &lt;to uri="mock:catchCamel"/&gt;
    &lt;/doCatch&gt;
    &lt;doFinally&gt;
       &lt;to uri="mock:finally"/&gt;
    &lt;/doFinally&gt;
  &lt;/doTry&gt;
&lt;/route&gt;</code></pre>
     </div>
    </div>
   </div>
   <div class="sect2">
    <h3 id="_use_end_to_end_the_block">
     <a class="anchor" href="#_use_end_to_end_the_block">
     </a>
     Use end() to end the block
    </h3>
    <div class="paragraph">
     <p>
      Notice when using Java DSL we must use
      <code>
       end()
      </code>
      to indicate where the try …​ catch …​ finally block ends. As the example above has a finally, then the
      <code>
       end()
      </code>
      should be at the end of the finally block. If we are not using a finally, then the
      <code>
       end()
      </code>
      should be at the end of the
      <code>
       doCatch
      </code>
      to indicate the end there.
     </p>
    </div>
    <div class="admonitionblock tip">
     <div class="table-wrapper">
      <table>
       <tr>
        <td class="icon">
         <i class="fa icon-tip" title="Tip">
         </i>
        </td>
        <td class="content">
         Instead of
         <code>
          end()
         </code>
         you can use
         <code>
          endDoTry()
         </code>
         to end and
         <em>
          return back
         </em>
         to the try …​ catch scope.
        </td>
       </tr>
      </table>
     </div>
    </div>
   </div>
   <div class="sect2">
    <h3 id="_using_nested_dotry_docatch_eips">
     <a class="anchor" href="#_using_nested_dotry_docatch_eips">
     </a>
     Using nested doTry …​ doCatch EIPs
    </h3>
    <div class="paragraph">
     <p>
      When nesting
      <code>
       doTry …​ doCatch
      </code>
      from an outer
      <code>
       doTry …​ doCatch
      </code>
      EIP, then pay extra attention when using Java DSL as the Java programming language is not
      <em>
       indent aware
      </em>
      so you may write Java code that is indented in a way where you think that a catch block is associated with the other doTry, but it is not.
     </p>
    </div>
    <div class="paragraph">
     <p>
      Given the following Java DSL:
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">from("direct:test").routeId("myroute")
    .doTry().
        doTry().
            throwException(new IllegalArgumentException("Forced by me"))
        .doCatch(Exception.class)
            .log("docatch 1")
            .throwException(new IllegalArgumentException("Second forced by me"))
    .doCatch(Exception.class)
        .log("docatch 2")
    .end();</code></pre>
     </div>
    </div>
    <div class="paragraph">
     <p>
      Then you may think that
      <code>
       <em>
        docatch2
       </em>
      </code>
      is associated on the outer doTry because of how the code is formatted. But it is
      <strong>
       not
      </strong>
      , both
      <code>
       <em>
        docatch1
       </em>
      </code>
      and
      <code>
       <em>
        docatch2
       </em>
      </code>
      are in the inner
      <code>
       doTry
      </code>
      , and the outer
      <code>
       doTry
      </code>
      has no catch blocks.
     </p>
    </div>
    <div class="paragraph">
     <p>
      So in this example, the route will throw the first exception which is then handled in
      <code>
       <em>
        docatch1
       </em>
      </code>
      which then throws a second exception, that is not caught.
     </p>
    </div>
    <div class="paragraph">
     <p>
      So what you must do is to end the doCatch block correct (notice how we use
      <code>
       endDoTry()
      </code>
      two times) as shown below:
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-java hljs" data-lang="java">from("direct:test").routeId("myroute")
    .doTry().
        doTry().
            throwException(new IllegalArgumentException("Forced by me"))
        .doCatch(Exception.class)
            .log("docatch 1")
            .throwException(new IllegalArgumentException("Second forced by me"))
         .endDoTry() // end this doCatch block
     .endDoTry() // end the inner doTry
    .doCatch(Exception.class)
        .log("docatch 2")
    .end();</code></pre>
     </div>
    </div>
    <div class="paragraph">
     <p>
      And by using the
      <code>
       endDoTry()
      </code>
      we can end the block correctly, and an XML representation of the route would be as follows:
     </p>
    </div>
    <div class="listingblock">
     <div class="content">
      <pre class="highlightjs highlight"><code class="language-xml hljs" data-lang="xml">&lt;route&gt;
    &lt;from uri="direct:test"/&gt;
    &lt;doTry&gt;
        &lt;doTry&gt;
            &lt;throwException id="throwException1"/&gt;
            &lt;doCatch id="doCatch1"&gt;
                &lt;log id="log1" message="docatch 1"/&gt;
                &lt;throwException id="throwException2"/&gt;
            &lt;/doCatch&gt;
        &lt;/doTry&gt;
        &lt;doCatch id="doCatch2"&gt;
            &lt;log id="log2" message="docatch 2"/&gt;
        &lt;/doCatch&gt;
    &lt;/doTry&gt;
&lt;/route&gt;</code></pre>
     </div>
    </div>
   </div>
  </div>
 </div>
</article>
